/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package state;

import java.awt.Image;

/**
 *
 * @author dougglas
 */
public class TelaSemaforo extends javax.swing.JFrame {
    /**
     * Creates new form TelaSemaforo
     */
    public TelaSemaforo() {
        initComponents();
        this.red.setVisible( false );
        this.yellow.setVisible( false );
        this.green.setVisible( false );
    }

    public void enableVerde () {
        this.red.setVisible( false );
        this.green.setVisible( true );
    }

    public void enableAmarelo () {
        this.green.setVisible( false );
        this.yellow.setVisible( true );
    }

    public void enableVermelho () {
        this.yellow.setVisible( false );
        this.red.setVisible( true );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        red = new javax.swing.JLabel();
        yellow = new javax.swing.JLabel();
        green = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        red.setIcon(new javax.swing.ImageIcon(getClass().getResource("/state/vermelho.png"))); // NOI18N
        getContentPane().add(red, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        yellow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/state/amarelo.png"))); // NOI18N
        getContentPane().add(yellow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        green.setIcon(new javax.swing.ImageIcon(getClass().getResource("/state/verde.png"))); // NOI18N
        getContentPane().add(green, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSemaforo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSemaforo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSemaforo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSemaforo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSemaforo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel green;
    private javax.swing.JLabel red;
    private javax.swing.JLabel yellow;
    // End of variables declaration//GEN-END:variables
}
